version: "3.5"

services:
  node:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - 80 # use a reverse proxy like Traefik
    ports:
      - 80:4567

  db:
    image: postgres:13.1-alpine
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nodebb
    volumes:
      - mongo:/data/db
    ports:
      - 5432:5432

volumes:
  mongo:
